"use client";

import { useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowDown, ArrowUp, CheckCircle2, ChevronRight, Download, Filter, Mail, MousePointerClick, RefreshCw, Search, Send, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { mailings, newsletterTypes, segments, trendData } from "./mock-data";

const typeColors: Record<string, string> = {"Psykologernes Nyhedsbrev":"#2b718f","TR/AMR Nyt":"#78598f","Magasinet P":"#c05a45",Kompetencenyt:"#2c8a78",Medlemskommunikation:"#b27b1f"};
const pct = (v:number) => `${v.toLocaleString("da-DK",{maximumFractionDigits:1})} %`;
const num = (v:number) => v.toLocaleString("da-DK");

export function Dashboard(){
  const [type,setType]=useState("Alle udsendelsestyper"); const [period,setPeriod]=useState("Seneste 12 måneder"); const [query,setQuery]=useState("");
  const [view,setView]=useState<"overview"|"mailings"|"segments"|"quality">("overview"); const [sync,setSync]=useState(false);
  const rows=useMemo(()=>mailings.filter(m=>(type==="Alle udsendelsestyper"||m.type===type)&&m.title.toLowerCase().includes(query.toLowerCase())),[type,query]);
  const latest=rows[0]??mailings[0];
  const refresh=()=>{setSync(true);window.setTimeout(()=>setSync(false),1800)};
  return <div className="app-shell"><a className="skip-link" href="#main">Gå til indhold</a>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">dp</div><div><strong>Dansk Psykolog Forening</strong><span>Udsendelsesdashboard</span></div></div>
      <nav aria-label="Primær navigation"><Nav active={view==="overview"} onClick={()=>setView("overview")} icon={<Activity/>} label="Overblik"/><Nav active={view==="mailings"} onClick={()=>setView("mailings")} icon={<Mail/>} label="Udsendelser"/><Nav active={view==="segments"} onClick={()=>setView("segments")} icon={<Users/>} label="Segmenter"/><Nav active={view==="quality"} onClick={()=>setView("quality")} icon={<CheckCircle2/>} label="Datakvalitet"/></nav>
      <div className="sidebar-note"><span className="status-dot"/>Prototype med syntetiske data</div></aside>
    <main id="main" className="main"><header className="topbar"><div><p className="eyebrow">Analyse af medlemskommunikation</p><h1>{view==="overview"?"Overblik":view==="mailings"?"Udsendelser":view==="segments"?"Segmenter":"Datakvalitet"}</h1></div><div className="sync-box"><div><span>Senest opdateret</span><strong>7. sep. 2026 kl. 13.00</strong></div><button className="refresh-button" onClick={refresh} disabled={sync}><RefreshCw className={sync?"spin":""}/>{sync?"Opdatering i kø":"Opdater nu"}</button></div></header>
      <section className="filters" aria-label="Filtre"><label><span>Periode</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Seneste 12 måneder</option><option>Seneste 6 måneder</option><option>2026</option></select></label><label><span>Udsendelsestype</span><select value={type} onChange={e=>setType(e.target.value)}><option>Alle udsendelsestyper</option>{newsletterTypes.map(t=><option key={t}>{t}</option>)}</select></label><label className="search-field"><span>Søg</span><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Søg efter udsendelse"/></div></label><button className="export"><Download/>Eksportér</button></section>
      {view==="overview"&&<Overview latest={latest} type={type} period={period}/>} {view==="mailings"&&<Mailings rows={rows}/>} {view==="segments"&&<Segments/>} {view==="quality"&&<Quality/>}
    </main></div>
}

function Nav({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string}){return <button className={active?"nav-item active":"nav-item"} onClick={onClick}>{icon}<span>{label}</span><ChevronRight/></button>}

function Overview({latest,type,period}:{latest:(typeof mailings)[number];type:string;period:string}){
 const trend=type==="Alle udsendelsestyper"?trendData:trendData.map(d=>({...d,click:Math.max(6,d.click-1.4),open:Math.max(39,d.open-3.2)}));
 return <div className="dashboard-grid"><div className="notice"><CheckCircle2/><div><strong>Datagrundlaget er komplet</strong><span>Alle 187 udsendelser er med i testdatasættet. Visningen dækker {period.toLowerCase()}.</span></div><button>Se datakvalitet</button></div>
  <section className="kpi-grid" aria-label="Nøgletal"><Kpi icon={<Send/>} label="Udsendelser" value="187" change="+12 fra forrige periode" positive/><Kpi icon={<Mail/>} label="Leverede mails" value="1,42 mio." change="98,9 % leveret" positive/><Kpi icon={<MousePointerClick/>} label="Klikrate" value="12,8 %" change="+1,6 procentpoint" positive/><Kpi icon={<Users/>} label="Åbningsrate" value="52,4 %" change="−2,1 procentpoint"/></section>
  <section className="panel trend-panel"><PanelHeader eyebrow="Udvikling" title="Klik- og åbningsrate" meta="Beregnet ud fra leverede mails"/><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid stroke="#dce5e8" vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`${v}%`} tickLine={false} axisLine={false}/><Tooltip formatter={v=>pct(Number(v))}/><Legend/><Line name="Åbningsrate" type="monotone" dataKey="open" stroke="#2b718f" strokeWidth={3} dot={false}/><Line name="Klikrate" type="monotone" dataKey="click" stroke="#c05a45" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div><p className="chart-note"><AlertTriangle/>Åbningsraten er påvirket af privatlivsfunktioner i mailklienter og er ikke det samme som faktisk læsning.</p></section>
  <section className="panel latest-panel"><PanelHeader eyebrow="Seneste udsendelse" title={latest.type} meta={latest.date}/><h3>{latest.title}</h3><div className="latest-stats"><Stat label="Leveret" value={num(latest.delivered)}/><Stat label="Åbnet" value={pct(latest.openRate)}/><Stat label="Klikket" value={pct(latest.clickRate)}/></div><div className="subject"><span>Emnefelt</span><p>{latest.subject}</p></div><button className="text-link">Se hele udsendelsen <ChevronRight/></button></section>
  <section className="panel content-panel"><PanelHeader eyebrow="Indhold" title="Mest klikkede nyheder" meta="Unikke klik / faktiske modtagere"/><div className="content-list">{latest.content.length?latest.content.map((item,i)=><div className="content-row" key={item.title}><span className="rank">{i+1}</span><div><strong>{item.title}</strong><span>{num(item.recipients)} modtagere · {num(item.clicks)} unikke klik</span></div><b>{pct(item.rate)}</b></div>):<p className="empty">Ingen indholdsdata i denne testudsendelse.</p>}</div></section>
  <section className="panel mix-panel"><PanelHeader eyebrow="Fordeling" title="Klikrate pr. udsendelsestype" meta="Mindst 4 udsendelser og 20.000 leverede mails"/><div className="chart-wrap small"><ResponsiveContainer width="100%" height="100%"><BarChart data={newsletterTypes.map((name,i)=>({name:name.replace("Psykologernes ","Psyk. "),value:[14.2,11.1,8.7,13.6,9.3][i],color:typeColors[name]}))}><CartesianGrid stroke="#dce5e8" vertical={false}/><XAxis dataKey="name" tickLine={false} axisLine={false} interval={0} tick={{fontSize:11}}/><YAxis tickFormatter={v=>`${v}%`} tickLine={false} axisLine={false}/><Tooltip formatter={v=>pct(Number(v))}/><Bar dataKey="value" radius={[5,5,0,0]}>{newsletterTypes.map(n=><Cell key={n} fill={typeColors[n]}/>)}</Bar></BarChart></ResponsiveContainer></div></section>
 </div>
}

function Mailings({rows}:{rows:typeof mailings}){return <section className="panel table-panel"><PanelHeader eyebrow="187 udsendelser i alt" title="Søgbar udsendelsesoversigt" meta="Sorter efter dato, type eller resultat"/><div className="table-scroll"><table><thead><tr><th>Udsendelse</th><th>Type</th><th>Dato</th><th>Leveret</th><th>Åbnet</th><th>Klikket</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><strong>{m.title}</strong><span>{m.subject}</span></td><td><i style={{background:typeColors[m.type]}}/>{m.type}</td><td>{m.date}</td><td>{num(m.delivered)}</td><td>{pct(m.openRate)}</td><td><b>{pct(m.clickRate)}</b></td></tr>)}</tbody></table></div></section>}

function Segments(){return <div className="two-column"><section className="panel"><PanelHeader eyebrow="Psykologernes Nyhedsbrev" title="Resultat pr. målgruppe" meta="Klikrate beregnet ud fra faktiske modtagere"/><div className="segment-list">{segments.map(s=><div className="segment-row" key={s.name}><div><strong>{s.name}</strong><span>{num(s.recipients)} modtagere · {num(s.clicks)} unikke klik</span></div><div className="bar-track"><span style={{width:`${Math.min(100,s.rate*4)}%`,background:s.color}}/></div><b>{pct(s.rate)}</b></div>)}</div></section><section className="panel insight-panel"><PanelHeader eyebrow="Automatisk observation" title="Det kan være værd at undersøge" meta="Sammenhæng – ikke dokumenteret effekt"/><div className="insight"><ArrowUp/><div><strong>Selvstændige klikker oftere</strong><p>Segmentet ligger 5,8 procentpoint over nyhedsbrevets samlede klikrate. Forskellen kan hænge sammen med nyheden om ledige ydernumre.</p></div></div><div className="insight neutral"><Filter/><div><strong>Grundlaget er tilstrækkeligt</strong><p>Analysen omfatter 5 udsendelser og 26.480 leverede mails i segmentet.</p></div></div></section></div>}

function Quality(){return <div className="quality-grid"><section className="panel score-card"><div className="score-ring"><strong>94</strong><span>af 100</span></div><div><p className="eyebrow">Samlet datakvalitet</p><h2>Godt grundlag</h2><p>De vigtigste udsendelses- og linkdata er komplette. To mappinger kræver opmærksomhed.</p></div></section><section className="panel"><PanelHeader eyebrow="Kontroller" title="Datakvalitet" meta="Seneste automatiske kontrol"/><QualityRow status="ok" title="Ingen persondata i output" text="Kontrol bestået kl. 13.01"/><QualityRow status="ok" title="Alle udsendelser har stabile id'er" text="187 af 187"/><QualityRow status="warn" title="Manglende udsendelsestag" text="3 udsendelser er placeret i 'Ikke kategoriseret'"/><QualityRow status="warn" title="Ukendt medlemsfelt" text="'Tilpasset felt 8' mangler en dokumenteret mapping"/></section><section className="panel sync-history"><PanelHeader eyebrow="Drift" title="Seneste kørsler" meta="Timebaseret opdatering"/>{["13.00","12.01","11.03","10.01"].map((t,i)=><div key={t}><CheckCircle2/><span>7. sep. 2026 kl. {t}</span><b>{i===0?"1.248 poster":"Ingen ændringer"}</b></div>)}</section></div>}

function Kpi({icon,label,value,change,positive}:{icon:React.ReactNode;label:string;value:string;change:string;positive?:boolean}){return <article className="kpi"><div className="kpi-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small className={positive?"positive":"negative"}>{positive?<ArrowUp/>:<ArrowDown/>}{change}</small></article>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function PanelHeader({eyebrow,title,meta}:{eyebrow:string;title:string;meta:string}){return <div className="panel-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><span>{meta}</span></div>}
function QualityRow({status,title,text}:{status:"ok"|"warn";title:string;text:string}){return <div className={`quality-row ${status}`}>{status==="ok"?<CheckCircle2/>:<AlertTriangle/>}<div><strong>{title}</strong><span>{text}</span></div></div>}
