"use client";
import { useState } from "react";
import { CartesianGrid, Line, LineChart, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { checkpointPolicy, checkpointStatus, comparisonPoint, normalLevel } from "../config/decision-methods.mjs";
import type { LiveMailing } from "./live-data";
import { EditorialNotes } from "./editorial-notes";
const format=(value:number)=>value.toLocaleString("da-DK",{maximumFractionDigits:1});
const time=(value:string)=>new Intl.DateTimeFormat("da-DK",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Copenhagen"}).format(new Date(value));

export function DecisionWorkbench({rows,selected,audience="",asOf,onOpen}:{rows:LiveMailing[];selected:LiveMailing;audience?:string;asOf:string;onOpen?:(id:string)=>void}){
  const [mode,setMode]=useState("history");
  const [metric,setMetric]=useState("clickRate");
  const [all,setAll]=useState(false);
  const normal=normalLevel(rows,selected,{audience,mode,metric,asOf});
  const chronological=rows.filter(row=>Date.parse(row.sentAt||"")<=Date.parse(selected.sentAt||"")).sort((a,b)=>Date.parse(a.sentAt||"")-Date.parse(b.sentAt||""));
  const visible=all?chronological:chronological.slice(-12);
  const points=visible.map(row=>{const point=comparisonPoint(row,audience,mode,metric);return {id:row.id,label:row.date,value:point.value,capturedAt:point.capturedAt};});
  const upper=Math.min(100,Math.max(10,Math.ceil(Math.max(...points.map(p=>p.value||0),normal.high||0)/10)*10));
  const label=metric==="clickRate"?"Klikrate":"Åbningsrate";
  const missing=mode!=="history"?checkpointStatus(selected,Number(mode),asOf):null;
  const candidates=selected.content.filter(item=>item.editorial?.kind==="news"&&item.clickMeasurement?.metric==="unique-contacts"&&item.clickMeasurement.aggregation==="single-link");
  const top=[...candidates].sort((a,b)=>b.clicks-a.clicks)[0];
  const unknown=selected.content.filter(item=>item.editorial?.kind==="unknown").length;
  return <>
    <section className="panel decision-workbench">
      <div className="panel-header"><div><p className="eyebrow">Til redaktionsmødet · {audience||"hele nyhedsbrevet"}</p><h2>{audience?"Målgruppens normale niveau":"Hvordan klarer udsendelsen sig?"}</h2></div><span>{selected.date}</span></div>
      <div className="decision-controls"><label>Målegrundlag<select aria-label="Målegrundlag" value={mode} onChange={e=>setMode(e.target.value)}><option value="history">Historik · vejledende</option><option value="1">Efter 1 døgn</option><option value="7">Efter 7 døgn</option></select></label><label>Vis i grafen<select aria-label="Vis i grafen" value={metric} onChange={e=>setMetric(e.target.value)}><option value="clickRate">Klikrate</option><option value="openRate">Åbningsrate</option></select></label></div>
      <p className="method-note">Valget gælder grafen, normalniveauet og rateobservationen. Øvrige nøgletal og linktabeller viser de seneste gemte værdier.</p>
      <p className="method-note">{mode==="history"?"Historikken består af målinger med forskellig alder. Sammenligningen er vejledende; ældre måledefinitioner er ikke fuldt dokumenteret. Udsendelser under 7 døgn sammenlignes endnu ikke.":`Faste målinger omkring ${mode} døgn efter afsluttet udsendelse, højst ${checkpointPolicy.toleranceHours} timer senere. Kun samme målepunkt og metodeversion sammenlignes. Målgruppens medlemsstatus på afsendelsesdagen er fortsat ikke bekræftet.`}</p>
      <div className="decision-readout"><article><span>{label} · valgt udsendelse</span><strong>{normal.current.value===null?"—":`${format(normal.current.value)} %`}</strong><small>{normal.current.capturedAt?`Målt ${time(normal.current.capturedAt)}`:mode==="history"?(!normal.mature?"Foreløbig · under 7 døgn":"Seneste gemte værdi"):"Intet målepunkt for dette valg"}</small></article><article><span>Normalniveau · median</span><strong>{normal.baseline===null?"—":`${format(normal.baseline)} %`}</strong><small>{normal.count} af højst 5 foregående udgaver · mindst 3 kræves</small></article><article><span>Forskel fra normalniveau</span><strong>{normal.delta===null?"—":`${normal.delta>0?"+":""}${format(normal.delta)} pct.point`}</strong><small>{normal.low!==null?`Tidligere spænd: ${format(normal.low)}–${format(normal.high!)} %`:!normal.mature?"Udsendelsen er stadig under 7 døgn":"Endnu ikke tilstrækkeligt grundlag"}</small></article></div>
      {missing&&normal.current.value===null?<p className="decision-gap">{missing.status==="historical"?"Denne historiske udsendelse har ingen faste målepunkter. Vælg Historik for at se de bevarede værdier.":missing.status==="missed"?"Måletidspunktet blev ikke opsamlet inden for tidsvinduet. Det genskabes ikke bagefter.":missing.status==="captured"?"Det samlede målepunkt findes, men denne målgruppes tal mangler ved måletidspunktet.":"Målepunktet afventer tidspunktet eller næste vellykkede dataopdatering."}</p>:null}
      <div className="decision-chart" role="img" aria-label={`${label} for ${audience||"hele udsendelsen"}. De præcise værdier findes under Vis grafens data.`}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:20,right:24,left:0,bottom:8}}><CartesianGrid stroke="#dce5e8" vertical={false}/><XAxis dataKey="id" tickFormatter={id=>points.find(p=>p.id===id)?.label||""} tickLine={false} minTickGap={35}/><YAxis domain={[0,upper]} tickFormatter={n=>`${n} %`} width={48}/><Tooltip labelFormatter={id=>points.find(p=>p.id===id)?.label||""} formatter={value=>[`${format(Number(value))} %`,label]}/>{normal.low!==null?<ReferenceArea y1={normal.low} y2={normal.high!} fill="#7895b6" fillOpacity={.12}/>:null}{normal.baseline!==null?<ReferenceLine y={normal.baseline} stroke="#687a93" strokeDasharray="5 4" label={{value:"Median",position:"insideTopRight"}}/>:null}<Line isAnimationActive={false} name={label} type="linear" dataKey="value" stroke={metric==="clickRate"?"#b24b37":"#2b718f"} strokeWidth={3} connectNulls={false} dot={{r:3}} activeDot={{r:5}}/></LineChart></ResponsiveContainer></div>
      <p className="method-note">Ét punkt pr. udsendelse. Manglende målinger tegnes som huller, aldrig som nul. Stiplet linje er normalniveauet for den valgte udsendelse; det lyse område er de tidligere udgavers minimum–maksimum, ikke et statistisk sikkerhedsinterval.</p>
      {chronological.length>12?<button type="button" className="expand-table" onClick={()=>setAll(!all)} aria-expanded={all}>{all?"Vis seneste 12 i grafen":`Vis alle ${chronological.length} i grafen`}</button>:null}
      <details className="decision-evidence"><summary>Se sammenligningsgrundlaget · {normal.count} udgaver</summary><p>Op til fem tidligere udgaver i den valgte periode, samme målgruppe og højst 25 % forskel i {audience?"modtagerantal":"leveringstal"}. Medianen vægter hver udgave ens. {normal.excluded} tidligere udgaver er fravalgt på grund af manglende måling, målemetode, størrelse eller alder.</p><ul>{normal.used.map((point: ReturnType<typeof comparisonPoint>)=><li key={point.mailing.id}>{point.mailing.date} · {format(point.value)} % · {format(point.size)} {audience?"modtagere":"leverede"} {onOpen?<button type="button" className="row-link" onClick={()=>onOpen(point.mailing.id)}>Åbn udsendelse</button>:null}</li>)}</ul></details>
      <details className="decision-evidence"><summary>Vis grafens data</summary><div className="table-scroll"><table><thead><tr><th>Dato</th><th>{label}</th><th>Måletidspunkt</th></tr></thead><tbody>{points.map(point=><tr key={point.id}><td>{point.label}</td><td>{point.value===null?"Mangler":`${format(point.value)} %`}</td><td>{point.capturedAt?time(point.capturedAt):mode==="history"?"Historisk / løbende":"Ikke opsamlet"}</td></tr>)}</tbody></table></div></details>
    </section>
    <section className="panel documented-observations"><p className="eyebrow">Dokumenterede observationer · {selected.date}</p><h2>Hvad kan vi sige ud fra tallene?</h2><ul>
      <li>{normal.delta===null?(!normal.mature?"Udsendelsen er endnu under 7 døgn. Resultatet er foreløbigt, så forskellen fra normalniveauet beregnes ikke endnu.":`Der er ikke tilstrækkeligt sammenligningsgrundlag for ${label.toLowerCase()} med det valgte målegrundlag.`):`${label} er ${format(Math.abs(normal.delta))} procentpoint ${normal.delta>=0?"over":"under"} medianen for ${normal.count} tidligere udgaver${audience?` hos ${audience}`:""}. ${mode==="history"?"Historisk sammenligning er vejledende.":"Udgaverne er målt ved samme faste målepunkt."}`} <span>Grundlag: Se sammenligningsgrundlaget ovenfor.</span></li>
      {!audience&&top?<li>“{top.editorial?.title||top.title}” har flest registrerede kontakter blandt de {candidates.length} nyhedslinks med et dokumenteret kontaktmål for en enkelt linkplacering: {format(top.clicks)}. <span>Grundlag: Hele udsendelsens linktabel. Gentagne linkplaceringer og uafklarede klikmål indgår ikke i denne rangering.</span></li>:null}
      {unknown>0?<li>{unknown} indholdsresultater i udsendelsen står til redaktionel gennemgang og indgår ikke i automatiske emneobservationer.<span>Grundlag: Vælg “Til gennemgang” i indholdsfilteret.</span></li>:null}
    </ul><p className="method-note">Observationerne beskriver de gemte målinger. De dokumenterer ikke årsager, menneskelige klik eller effekten af en bestemt overskrift. Linkresultaterne er løbende/historiske værdier, også når grafen viser et fast målepunkt.</p></section>
    <CheckpointSummary mailing={selected} asOf={asOf}/>
    <EditorialNotes key={`${selected.id}-${audience}`} mailingId={selected.id} audience={audience} title={`${selected.date} · ${selected.title}`}/>
  </>;
}
export function CheckpointSummary({mailing,asOf}:{mailing:LiveMailing;asOf:string}){
  return <details className="panel checkpoint-summary"><summary>Faste målepunkter · 1 og 7 døgn</summary><p>Opsamlingen gælder udsendelser fra 17. september 2026. Målinger gemmes én gang og bevares i versionshistorikken. Tabellen bruger tidspunktet for dashboardets seneste dataopdatering.</p><ul>{checkpointPolicy.days.map(day=>{const result=checkpointStatus(mailing,day,asOf);return <li key={day}><strong>Efter {day} døgn:</strong> {result.point?`${time(result.point.capturedAt)} · faktisk alder ${format(result.point.ageHours)} timer · ${result.point.segmentPerformance.length} målgrupper`:result.status==="historical"?"Ikke opsamlet for historiske udsendelser":result.status==="missed"?"Mistet målepunkt — tidsvinduet er overskredet":result.status==="due"?"Tidspunkt nået; endnu ikke opsamlet":"Afventer måletidspunkt"}</li>;})}</ul></details>;
}
